In [1]:
img_id = "CA164432V0024"

In [2]:
georef_fld = "/data_1/ATM/data_1/georef/sat"

In [3]:
import numpy as np

transformation_matrix = np.loadtxt(georef_fld + "/" + img_id + "_transform.txt")
print(transformation_matrix)

[[-5.12180000e-01 -1.04113000e+00 -1.67324267e+06]
 [-1.05756000e+00  5.00730000e-01  9.16546298e+05]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [4]:
import src.export.export_world_file as ewf
ewf.export_world_file(transformation_matrix, f"/home/fdahle/Desktop/test/{img_id}.tfw")

World file exported successfully to /home/fdahle/Desktop/CA164432V0024.tfw
